Remove core.jdbc package and adopt Spring DI.
But there are following error when launching a program.
java.lang.IllegalStateException: Lifecycle method annotation requires a
no-arg method: public void
next.support.context.ContextLoaderListener.contextInitialized(javax.servlet.ServletContextEvent)